name: main
on: [push]
jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Run Unit Test
        run: node dist/Test1.js
